PreCommit:
  RuboCop:
    enabled: true
    on_warn: fail
  SlimLint:
    enabled: true
    include: app/views/**/*.slim
  TrailingWhitespace:
    exclude:
      - 'config/*'
      - 'db/*'

PostCommit:
  GitGuilt:
    enabled: true
    flags: ["HEAD~", "HEAD"]